### ISSUE TITLE
Als Plugin?

### ISSUE THREAD

**Issue by eaCe** [alexplusde/sked_ics#11]
Wäre es nicht angenehmer dieses Addon als Plugin für Sked anzubieten?

**Comment by alexplusde** [comment]
Doch, klar, aber da sich das noch in Entwicklung befindet, keiner mitmacht und ein paar Dinge abzustimmen sind, möchte ich sowas Halbgares noch nicht zu FOR und in Sked schieben.

Ich erhoffe mir des Weiteren, dass mal jemand auf das Addon im Installer aufmerksam wird und vielleicht doch mitmachen möchte / testet.

**Comment by eaCe** [comment]
Ich als Android nutzer kann da nicht so viel beitragen ;) aber ich kann mich dem JSON-LD annehmen. 
Allerdings müssste man dann auch die custom-fields beachten und wissen welches benötigt wird...

**Comment by skerbis** [comment]
Ich verstehe das AddOn nicht. Wenn ich auf den Reiter ics clicke passiert nix

**Comment by alexplusde** [comment]
@skerbis sehr konstruktiv. Ich habe mit der Entwicklung angefangen und komme an einigen Stellen und zeitlich nicht voran. Dieses Addon ist weit weg von produktiv. Und es gibt ja ungelöste Themen in sked wie das mit den ganztägigen Terminen.

Du kannst dir bspw. den Cronjob anschauen.

**Comment by skerbis** [comment]
@alexplusde Sorry. Leider war nicht sofort ersichtlich was man bereits machen kann.  Hier geht's weiter: https://github.com/alexplusde/sked_ics/issues/12
